-- Table: public.user_info

DROP TABLE IF EXISTS public.user_info;

CREATE TABLE public.user_info
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    given_name character varying(255) COLLATE pg_catalog."default",
    salutation character varying(255) COLLATE pg_catalog."default",
    surname character varying(255) COLLATE pg_catalog."default",
    user_sex character varying(255) COLLATE pg_catalog."default",
    user_status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_info_pkey PRIMARY KEY (user_id)
);
